# When it happens
on:
  push:
    branches:
      - main
      
  workflow_dispatch:

  
# what it does
jobs:
  example:
    name: "Example job"
    runs-on: "ubuntu-latest"
    steps: 
      - name: "Step 1"
        run: echo "hi!"
      - name: "Step 2"
        run: echo "hi!"

  quality_check:
    name: "Quality Check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get repo"
        uses: actions/checkout@v6
        
        
      - name: "Install Python"
        uses: actions/setup-python@v6
        
      - name: "Install libraries"
        run: pip install -r requirements.txt

      - name: "Run tests"
        run: pytest
      



# {
#   key: 1,
#   key2: 5
# }
